version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: jungleran/drupal:8.6.0-beta2
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      
 
